import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class AllQ extends javax.swing.JFrame {

    /**
     * Creates new form AllQ
     */
    public AllQ() {
        initComponents();
         Connection con;
           try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("Select * from question");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                System.out.println(rs.getInt("id"));
                Object obj[] = {rs.getInt("id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("ans")};
                tm1.addRow(obj);
            }
            
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       if(jRadioButton2.isSelected()){
              try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("Select * from sports");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                System.out.println(rs.getInt("s_id"));
              Object obj[] = {rs.getInt("s_id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("ans")};
                tm1.addRow(obj);
            }
           
           
        } 
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
               }
       if(jRadioButton3.isSelected()){
              try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
           Statement st = con.createStatement();
           
           ResultSet rs = st.executeQuery("Select * from logo");
           DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
           tm1.setRowCount(0);
           while(rs.next()){
              System.out.println(rs.getInt("l_id"));
                Object obj[] = {rs.getInt("l_id"), rs.getString("logo"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("ans")};
                tm1.addRow(obj);
           }
           
           
       } 
       catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
       }
        }
        if(jRadioButton4.isSelected()){
              try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
           Statement st = con.createStatement();
           
            ResultSet rs = st.executeQuery("Select * from history");
           DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
               System.out.println(rs.getInt("h_id"));
                Object obj[] = {rs.getInt("h_id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("ans")};
                tm1.addRow(obj);
           }
            
            
       } 
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
       }
       }  
    
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(150, 183));
        setMaximumSize(new java.awt.Dimension(1250, 500));
        setMinimumSize(new java.awt.Dimension(1250, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\OneDrive\\Documents\\NetBeansProjects\\JavaApplication1\\src\\all questions.png")); // NOI18N
        jLabel1.setText("All Question");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 60, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 10));

        jTable4.setAutoCreateRowSorter(true);
        jTable4.setBackground(new java.awt.Color(255, 221, 55));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Question", "op1", "op2", "op3", "op4", "Answer"
            }
        ));
        jTable4.setMaximumSize(new java.awt.Dimension(105, 80));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1230, 220));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 204, 255));
        jRadioButton1.setText("GK");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 204, 255));
        jRadioButton2.setText("Sports");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(51, 204, 255));
        jRadioButton3.setText("Logo");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(51, 204, 255));
        jRadioButton4.setText("History");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1250, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        adminHome.open=0;
        setVisible(false);
        new adminHome().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
//            AllQ();
        }
             Connection con;
           try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("Select * from question");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                System.out.println(rs.getInt("id"));
                Object obj[] = {rs.getInt("id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("ans")};
                tm1.addRow(obj);
            }
            
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         if(jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
         }
             Connection con;
           try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("Select * from sports");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                System.out.println("Sports Id="+rs.getInt("s_id"));
                Object obj[] = {rs.getInt("s_id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("answer")};
                tm1.addRow(obj);
            }
            
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //}
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         if(jRadioButton3.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(false);
            jRadioButton4.setSelected(false);
         }
             Connection con;
          try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
           Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select * from logo");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
         tm1.setRowCount(0);
           while(rs.next()){
                System.out.println(rs.getInt("l_id"));
                Object obj[] = {rs.getInt("l_id"), rs.getString("logo"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("answer")};
                tm1.addRow(obj);
           }
           }
         
          
       
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
       
        }
    
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
         }
        Connection con;
           try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/quiztime","root","");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("Select * from history");
            DefaultTableModel tm1 = (DefaultTableModel)jTable4.getModel();
            tm1.setRowCount(0);
            while(rs.next()){
                System.out.println("history Id="+rs.getInt("h_id"));
                Object obj[] = {rs.getInt("h_id"), rs.getString("Question"), rs.getString("op1"), rs.getString("op2"),rs.getString("op3"),rs.getString("op4"),rs.getString("answer")};
                tm1.addRow(obj);
            }
             } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AllQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

//    private void initComponents() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
